spring:
  application:
    name: zahra-api
  datasource:
    url: jdbc:postgresql://localhost:5433/zahra_db
    username: nabgha
    password: 44026676
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
